#version: "3.9"
services:
  web:
   #container_name: python-server
   command: python main.py
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "8000:8000"
   volumes:
     - ./app/my-app:/app

  grafana:
    container_name: grafana-server
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    user: "1000"
  prometheus:
    container_name: prometheus-server
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro


  postgres:
    container_name: postgres-server
    image: postgres:16
    ports:
      - 5432:5432
    volumes:
      - ./backup:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test

  postgres-exporter:
    container_name: postgres-exporter
    image: prometheuscommunity/postgres-exporter
    volumes:
      - ./queries.yaml:/etc/postgres_exporter/queries.yaml
    ports:
      - 9187:9187
    environment:
      #PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/test?sslmode=disable"
    command:
      - "--extend.query-path=/etc/postgres_exporter/queries.yaml"
    links:
      - postgres
      - prometheus


